const seed=[{id:'1',company:'Accenture',role:'Application Developer',location:'Hyderabad',salary:'₹4–7 LPA',status:'Interview',priority:'High',date:'2026-10-01',followUp:'2026-10-06',notes:'Technical interview scheduled.'},{id:'2',company:'TCS',role:'Java Full Stack Developer',location:'Hyderabad',salary:'₹3.5–5 LPA',status:'Applied',priority:'Medium',date:'2026-10-02',followUp:'2026-10-08',notes:''},{id:'3',company:'Cognizant',role:'Programmer Analyst',location:'Bengaluru',salary:'₹4–6 LPA',status:'Applied',priority:'High',date:'2026-10-03',followUp:'2026-10-09',notes:''},{id:'4',company:'IBM',role:'Data Analyst',location:'Remote',salary:'₹5–8 LPA',status:'Rejected',priority:'Low',date:'2026-09-28',followUp:'',notes:'Keep profile updated.'}];
let apps=JSON.parse(localStorage.getItem('jobtrack_apps')||'null')||seed;const $=id=>document.getElementById(id);const today=new Date().toISOString().slice(0,10);let toastTimer;
function save(){localStorage.setItem('jobtrack_apps',JSON.stringify(apps));render()}
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function statusCount(s){return apps.filter(a=>a.status===s).length}
function renderStats(){$('totalStat').textContent=apps.length;$('interviewStat').textContent=statusCount('Interview');$('offerStat').textContent=statusCount('Offer');const responses=apps.filter(a=>['Interview','Offer','Rejected'].includes(a.status)).length;$('responseStat').textContent=apps.length?Math.round(responses/apps.length*100)+'%':'0%';const max=Math.max(apps.length,1);$('pipelineRows').innerHTML=['Applied','Interview','Offer','Rejected'].map(s=>`<div class="pipeline-row"><span class="pipeline-label">${s}</span><div class="bar"><span style="width:${statusCount(s)/max*100}%"></span></div><span class="count">${statusCount(s)}</span></div>`).join('')}
function renderFollowUps(){const list=apps.filter(a=>a.followUp&&a.followUp>=today).sort((a,b)=>a.followUp.localeCompare(b.followUp)).slice(0,4);$('followUps').innerHTML=list.length?list.map(a=>`<div class="follow"><div><strong>${esc(a.company)}</strong><small>${esc(a.role)}</small></div><small>${fmt(a.followUp)}</small></div>`).join(''):'<div class="empty">No upcoming follow-ups.</div>'}
function filtered(){const q=$('searchInput').value.toLowerCase(),s=$('statusFilter').value,p=$('priorityFilter').value;return apps.filter(a=>(!q||`${a.company} ${a.role} ${a.location}`.toLowerCase().includes(q))&&(s==='all'||a.status===s)&&(p==='all'||a.priority===p)).sort((a,b)=>b.date.localeCompare(a.date))}
function row(a){return `<tr><td><span class="company-cell">${esc(a.company)}</span><span class="sub">${esc(a.role)}</span></td><td>${esc(a.location||'—')}</td><td><span class="badge ${a.status}">${a.status}</span></td><td><span class="priority ${a.priority}">${a.priority}</span></td><td>${fmt(a.date)}</td><td><div class="actions"><button class="action" onclick="editApp('${a.id}')">Edit</button><button class="action" onclick="deleteApp('${a.id}')">Delete</button></div></td></tr>`}
function table(list){if(!list.length)return '<div class="empty">No applications match your filters.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Company / Role</th><th>Location</th><th>Status</th><th>Priority</th><th>Date</th><th></th></tr></thead><tbody>${list.map(row).join('')}</tbody></table></div>`}
function renderTables(){const sorted=[...apps].sort((a,b)=>b.date.localeCompare(a.date));$('recentTable').innerHTML=table(sorted.slice(0,5));$('applicationsTable').innerHTML=table(filtered())}
function render(){renderStats();renderFollowUps();renderTables()}
function fmt(d){if(!d)return '—';return new Date(d+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function openModal(app){$('modal').classList.remove('hidden');$('modalTitle').textContent=app?'Edit application':'Add application';$('appId').value=app?.id||'';$('company').value=app?.company||'';$('role').value=app?.role||'';$('location').value=app?.location||'';$('salary').value=app?.salary||'';$('status').value=app?.status||'Applied';$('priority').value=app?.priority||'Medium';$('date').value=app?.date||today;$('followUp').value=app?.followUp||'';$('notes').value=app?.notes||'';$('company').focus()}
function closeModal(){$('modal').classList.add('hidden')}
window.editApp=id=>openModal(apps.find(a=>a.id===id));window.deleteApp=id=>{if(confirm('Delete this application?')){apps=apps.filter(a=>a.id!==id);save();showToast('Application deleted')}};
$('appForm').addEventListener('submit',e=>{e.preventDefault();const id=$('appId').value;const item={id:id||Date.now().toString(),company:$('company').value.trim(),role:$('role').value.trim(),location:$('location').value.trim(),salary:$('salary').value.trim(),status:$('status').value,priority:$('priority').value,date:$('date').value,followUp:$('followUp').value,notes:$('notes').value.trim()};if(id)apps=apps.map(a=>a.id===id?item:a);else apps.push(item);save();closeModal();showToast(id?'Application updated':'Application added')});
$('addBtn').onclick=()=>openModal();$('heroAdd').onclick=()=>openModal();$('closeModal').onclick=closeModal;$('cancelBtn').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});$('searchInput').oninput=renderTables;$('statusFilter').onchange=renderTables;$('priorityFilter').onchange=renderTables;
function go(section){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active-section'));$(section).classList.add('active-section');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section===section));$('pageTitle').textContent=section==='dashboard'?'Dashboard':'Applications'}
document.querySelectorAll('[data-section]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.section)));
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(apps,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='jobtrack-applications.json';a.click();URL.revokeObjectURL(a.href);showToast('Applications exported')};render();
